### ISSUE TITLE
Mysql

### ISSUE THREAD

**Issue by LuanMartins** [especializati/setup-docker-laravel#10]
Não consigo me conectar ao container do mysql através de um cliente, como por exemplo workbench ou dbeaver. Precisa de alguma configuração adicional para funcionar?

**Comment by bubaluza** [comment]
> Não consigo me conectar ao container do mysql através de um cliente, como por exemplo workbench ou dbeaver. Precisa de alguma configuração adicional para funcionar?

Para qual porta voce está tentando conectar? Pois no docker-compose está sendo exposto a porta 3388 ao invez da padrão 3306. Esse tipo de exposição é justamente para evitar conflitos entre outras imagens que você possa ter instalado, como por exemplo outro mysql.
https://github.com/especializati/setup-docker-laravel/blob/d52fadd033631fdf7757c90c836d6dfbd9fe323b/docker-compose.yml#L42

**Comment by LuanMartins** [comment]
Poxa, cara, era isso mesmo. Muito obrigado! Já tava tão estressado que nem me atentei rsrs
