### ISSUE TITLE
please add  certbot for ssl

### ISSUE THREAD

**Issue by vahidalvandi** [especializati/setup-docker-laravel#12]
hi . thank you , i want use docker in production and need let's scripts  ssl with https://hub.docker.com/r/certbot/certbot please add support do it

**Comment by ubiratanlima** [comment]
I dont know to make. Sorry. This expert contact... https://github.com/especializati

**Comment by carlosfgti** [comment]
Adicionado: https://github.com/especializati/setup-docker-laravel/tree/https
