### ISSUE TITLE
docker-compose exec app bash (`version` is obsolete)

### ISSUE THREAD

**Issue by rogeriorossi** [especializati/setup-docker-laravel#19]
Quando executo o comando docker-compose exec app bash dá a seguinte mensagem:

time="2024-06-13T22:26:56-03:00" level=warning msg="docker-compose.yml: `version` is obsolete"

**Comment by carlosfgti** [comment]
Na última atualização do Docker, não precisa mais informar o version no arquivo docker-compose.yaml, basta remover o version
