### ISSUE TITLE
useradd: invalid user ID '-d' ERROR: Service 'app' failed to build : The command '/bin/sh -c useradd -G www-data,root -u $uid -d /home/$user $user' returned a non-zero code: 3

### ISSUE THREAD

**Issue by RamonSaldanha** [especializati/setup-docker-laravel#5]
quando eu uso o comando "sudo docker-compose up -d" me aparece o erro:

useradd: invalid user ID '-d'
ERROR: Service 'app' failed to build : The command '/bin/sh -c useradd -G www-data,root -u $uid -d /home/$user $user' returned a non-zero code: 3

não sei o que fazer.

alguém poderia me ajudar?

**Comment by thobiasvicente** [comment]
No Dockerfile adiciona isso aqui.

ARG _user=_SEUNOME_
ARG uid=1000

**Comment by wmomesso** [comment]
Perfeito funcionou aqui para mim, mas uma dúvida, esse usuario é o mesmo da maquina local?

Tks.

**Comment by carlosfgti** [comment]
Pode ser qualquer usuário, porque é o usuário (não root) do container.
