### ISSUE TITLE
Erro de permissão ao rodar composer install

### ISSUE THREAD

**Issue by tiagoon** [especializati/setup-docker-laravel#7]
Estou recebendo um erro de permissão ao rodar o composer install. 
``` file_put_contents(./composer.lock): Failed to open stream: Permission denied  ```

Como solução estou setando a propriedade dentro do container  
``` 
chown -R tiago ./  
``` 

Assim funciona, mas não sei se é a melhor forma.

**Comment by carlosfgti** [comment]
Qual o seu sistema operacional? Linux?
Confere no Dockerfile se usou o mesmo usuário do seu S.O.

**Comment by oscarnascimento** [comment]
eu usei o mesmo usuario, mas mesmo assim o problema acontece, podes me ajudar @carlosfgti ? Eu uso um linux e sim, o usuário coloquei o mesmo do SO. Estou usando Docker Desktop

**Comment by tiagoon** [comment]
Tenta instalar somente a versão CLI do Docker, @oscarnascimento. Por aqui só resolveu assim.

**Comment by oscarnascimento** [comment]
> Tenta instalar somente a versão CLI do Docker, @oscarnascimento. Por aqui só resolveu assim.

poise, vou fazer isso sim. ta impossível desenvolver do jeito que ta rsrs

**Comment by tiagoon** [comment]
Eu desisti do Docker Desktop no ubuntu. Todas as vezes que tentei deu esse problema.
Resolvi assim:
- [Docker CLI](https://rosnertech.com.br/instalando-o-docker-no-ubuntu-22-04/)  
- [Whaler](https://flathub.org/pt-BR/apps/com.github.sdv43.whaler) - um cliente para gerenciar containers (é bem simplório, mas até você acostumar fazer tudo pelo terminal ele vai ser útil).

**Comment by oscarnascimento** [comment]
Boa

> Eu desisti do Docker Desktop no ubuntu. Todas as vezes que tentei deu esse problema. Resolvi assim:
> 
> * [Docker CLI](https://rosnertech.com.br/instalando-o-docker-no-ubuntu-22-04/)
> * [Whaler](https://flathub.org/pt-BR/apps/com.github.sdv43.whaler) - um cliente para gerenciar containers (é bem simplório, mas até você acostumar fazer tudo pelo terminal ele vai ser útil).

Boa meu caro! Eu vou aproveitar a oportunidade e me forçar a usar o docker por linha de comando, apesar de eu ter a interface do PHPStorm pra lidar com os containers, que também é bem simples. Mas vou testar essa ferramenta e indicar pro pessoal! Valeu. Vou verificar se o problema será resolvido com a desistencia do Docker Desktop Linux. Te atualizo.

**Comment by gseganzerla** [comment]
Como eu resolvi isso


adicionei essas duas variáveis no meu .env 

```
DOCKER_UID=1000
DOCKER_USER=gseganzerla

```


E adicionei no meu contêiner essas variáveis
> Docker-compose.yml


    pdv:
      build:
        args:
          user: ${DOCKER_USER}
          uid: ${DOCKER_UID}
        context: ./
        dockerfile: Dockerfile


E no Dockerfile utilizei elas dessa forma como o @carlosfgti disponibilizou
> Dockerfile

```
ARG user
ARG uid

/* Instruções para montar a imagem */

RUN useradd -G www-data,root -u $uid -d /home/$user $user
RUN mkdir -p /home/$user/.composer && \
    chown -R $user:$user /home/$user 


```


> Para pegar os valores das variáveis utilize 

`$ whoami` -> Nome de usuário

`$ echo $UID` -> UID do usuário

@oscarnascimento
